FROM postgres:17.6

RUN apt-get update && apt-get install -y --no-install-recommends postgresql-17-cron

ENV POSTGRES_DATABASE=reelfake_db_prod

COPY data/* /docker-entrypoint-initdb.d/
COPY scripts/init-prod.sql /docker-entrypoint-initdb.d/
RUN chmod a+r /docker-entrypoint-initdb.d/*

EXPOSE 5432

CMD [ "postgres", "-c", "max_wal_size=4GB", "-c", "shared_preload_libraries=pg_cron", "-c", "cron.database_name=reelfake_db_prod" ]