FROM postgres:17.6

RUN apt-get update && apt-get install -y --no-install-recommends postgresql-17-cron

ENV POSTGRES_DATABASE=reelfake_db

COPY data/* /docker-entrypoint-initdb.d/
COPY scripts/init-test.sql /docker-entrypoint-initdb.d/
RUN chmod a+r /docker-entrypoint-initdb.d/*

EXPOSE 5432